import { defineCollection } from 'astro:content'
import { z } from 'astro/zod'
import type { Loader } from 'astro/loaders'
import { docsLoader } from '@astrojs/starlight/loaders'
import { docsSchema } from '@astrojs/starlight/schema'

// DRAFTS. Starlight removed its own `draft` frontmatter (0.42 has no trace of
// it: a draft page silently BUILT and went live). So we own it: a page with
// `draft: true` is loaded in dev — outlines are useful while writing — and
// dropped from the store in a production build, before any route, sidebar
// entry or search index can see it. The sidebar is autogenerated for the same
// reason: a hand-written slug pointing at a dropped draft would fail the build.
//
// COMING SOON is the published counterpart of a draft: `comingSoon: true` puts
// a page on the live site with a banner and a "Soon" badge in the sidebar, so a
// visitor sees the area exists before its guide does. Applied here rather than
// written into each page, so every placeholder says it the same way and turning
// one into a real page is deleting one line.
const SOON_BANNER =
  'This guide is on its way. The feature may already be in your studio — ask us at <a href="mailto:hello@linyup.com">hello@linyup.com</a> if you need it now.'

type HelpData = {
  draft?: boolean
  comingSoon?: boolean
  banner?: { content: string }
  sidebar?: { badge?: unknown; [k: string]: unknown }
}

/** A coming-soon page with its banner and badge filled in, or null for any other. */
function withSoon<T extends { data: Record<string, unknown>; digest?: string | number }>(entry: T): T | null {
  const data = entry.data as HelpData
  if (!data.comingSoon) return null
  return {
    ...entry,
    // The store ignores a set whose digest is unchanged, so the rewritten entry
    // needs its own.
    digest: `${entry.digest ?? ''}:soon`,
    data: {
      ...entry.data,
      banner: data.banner ?? { content: SOON_BANNER },
      sidebar: { ...data.sidebar, badge: data.sidebar?.badge ?? { text: 'Soon', variant: 'note' } },
    },
  }
}

function helpDocs(inner: Loader): Loader {
  return {
    name: 'linyup-help-docs',
    load: async (context) => {
      // Intercept what the inner loader stores rather than patching the store
      // afterwards: the dev watcher re-stores an edited page through the same
      // `set`, and a page patched only once would lose its banner on first edit.
      const store = new Proxy(context.store, {
        get(target, prop, receiver) {
          if (prop !== 'set') return Reflect.get(target, prop, receiver)
          return (entry: Parameters<typeof target.set>[0]) => {
            if (import.meta.env.PROD && (entry.data as HelpData).draft) return false
            return target.set(withSoon(entry) ?? entry)
          }
        },
      })
      await inner.load({ ...context, store })
      // And sweep afterwards: the content cache persists between runs, and a
      // draft that `astro dev` stored could otherwise ride into a build whose
      // loader skipped the unchanged file without ever calling `set`.
      if (import.meta.env.PROD) {
        for (const [id, entry] of context.store.entries()) {
          if ((entry.data as HelpData).draft) context.store.delete(id)
        }
      }
    },
  }
}

export const collections = {
  docs: defineCollection({
    loader: helpDocs(docsLoader()),
    schema: docsSchema({
      extend: z.object({ draft: z.boolean().default(false), comingSoon: z.boolean().default(false) }),
    }),
  }),
}