import { defineCollection } from 'astro:content'
import { z } from 'astro/zod'
import type { Loader } from 'astro/loaders'
import { docsLoader } from '@astrojs/starlight/loaders'
import { docsSchema } from '@astrojs/starlight/schema'

// DRAFTS. Starlight removed its own `draft` frontmatter (0.42 has no trace of
// it: a draft page silently BUILT and went live). So we own it: a page with
// `draft: true` is loaded in dev — outlines are useful while writing — and
// dropped from the store in a production build, before any route, sidebar
// entry or search index can see it. The sidebar is autogenerated for the same
// reason: a hand-written slug pointing at a dropped draft would fail the build.
function withoutDraftsInProd(inner: Loader): Loader {
  return {
    name: 'linyup-help-docs',
    load: async (context) => {
      await inner.load(context)
      if (!import.meta.env.PROD) return
      for (const [id, entry] of context.store.entries()) {
        if ((entry.data as { draft?: boolean }).draft) context.store.delete(id)
      }
    },
  }
}

export const collections = {
  docs: defineCollection({
    loader: withoutDraftsInProd(docsLoader()),
    schema: docsSchema({ extend: z.object({ draft: z.boolean().default(false) }) }),
  }),
}