#!/usr/bin/env node
/**
 * Generates docs/README.md from frontmatter. `--check` fails if it is stale.
 *
 * GENERATED AND COMMITTED, like a lockfile. The primary reader of these docs is
 * a coding agent reading the repo from disk, frequently without running
 * anything — an index that only exists after `pnpm docs:index` is invisible to
 * the reader it is for. It is also reviewable in a PR diff and readable on
 * GitHub, neither of which a build step gives you. The same shape the repo
 * already trusts in pnpm-lock.yaml and in `pnpm i18n:check`.
 *
 * LISTS, NOT TABLES. `pnpm format` runs Prettier over every markdown file and Prettier
 * REALIGNS TABLE COLUMN PADDING — a generated table drifts out of byte-equality
 * the first time anyone formats, and `--check` then fails for no reason. A `-`
 * list line is Prettier-stable. (A .prettierignore would be worse: `format`
 * uses --ignore-path .gitignore, so adding one changes which files Prettier
 * touches repo-wide.)
 *
 * NO HARDCODED COUNTS. Any total here is emitted fresh on every run and gated
 * by byte-equality, so it is executable rather than a claim that rots — which
 * is what CLAUDE.md § "Comments must not assert a COUNT of code sites" asks for.
 *
 * NOTHING HERE COMES FROM `git log`. It carried a per-doc last-touched date
 * until 2026-09-17, and that date is not a property of the tree: it depends on
 * how deep the clone is and on whether HEAD is a merge. CI checks out depth 1,
 * so every file resolved to the HEAD commit's date; on a PR that is GitHub's
 * merge commit, which meant the whole index read as "today" and the check
 * failed on any day but the one it was generated. Deepening CI would not have
 * fixed it either — a contributor whose own clone is shallow (this repo is
 * routinely cloned that way) still could not regenerate a matching index. The
 * date was also the sort key for the archive section, so the ordering moved
 * with it. Everything emitted below is derived from the TREE alone.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseFrontmatter, AREAS } from './lib/docsMeta.mjs'

const ROOT = fileURLToPath(new URL('..', import.meta.url)).replace(/[\\/]$/, '')
const DOCS = join(ROOT, 'docs')
const OUT = join(DOCS, 'README.md')

const AREA_TITLE = {
  payments: 'Payments, billing and finance',
  booking: 'Booking — classes, appointments, waivers',
  contacts: 'Contacts and membership',
  content: 'Public content and localisation',
  platform: 'Platform, infrastructure and API',
  mobile: 'Member app',
  ops: 'Operations, launch and migration',
  product: 'Product, strategy and open registers',
}

const STATUS_NOTE = {
  living: 'how it works now',
  plan: 'work to do',
  record: 'true as of a date',
  closed: 'finished',
}

const walk = (d, out = []) => {
  for (const e of readdirSync(d)) {
    const f = join(d, e)
    if (statSync(f).isDirectory()) walk(f, out)
    else if (e.endsWith('.md')) out.push(relative(DOCS, f).replaceAll('\\', '/'))
  }
  return out
}

const docs = []
for (const rel of walk(DOCS).sort()) {
  if (rel === 'README.md' || rel.endsWith('/README.md')) continue
  const { data } = parseFrontmatter(readFileSync(join(DOCS, rel), 'utf8'))
  if (!data?.title) continue
  docs.push({ rel, ...data })
}

const line = (d) =>
  `- [**${d.title}**](./${d.rel}) — ${STATUS_NOTE[d.status] ?? d.status}`

const out = []
out.push('<!-- Generated by scripts/docs-index.mjs. Do not edit by hand; run `pnpm docs:index`. -->')
out.push('')
out.push('# Documentation index')
out.push('')
out.push('Every document under `docs/`, grouped by area. `CLAUDE.md` holds the invariants an')
out.push('agent must not violate and points here for the reasoning behind them.')
out.push('')
out.push('Each entry says what kind of document it is, because the difference decides whether')
out.push('you may act on it:')
out.push('')
out.push('- **how it works now** — describes the system today; the imperatives are rules.')
out.push('- **work to do** — a plan; the imperatives are tasks, and may be stale.')
out.push('- **true as of a date** — a point-in-time record, never re-run since. Verify against')
out.push('  the code before acting on it.')
out.push('- **finished** — closed. Nothing in it is a work list.')
out.push('')

const live = docs.filter((d) => d.status === 'living' || d.status === 'plan')
const past = docs.filter((d) => d.status === 'record' || d.status === 'closed')

for (const area of AREAS) {
  const rows = live.filter((d) => d.area === area)
  if (!rows.length) continue
  out.push(`## ${AREA_TITLE[area] ?? area}`)
  out.push('')
  for (const d of rows.sort((a, b) => a.title.localeCompare(b.title))) out.push(line(d))
  out.push('')
}

if (past.length) {
  out.push('## Closed and point-in-time')
  out.push('')
  out.push('Records of what was true on a date, and finished work. Kept because a closed plan')
  out.push('is often the only place a decision\'s reasoning survives. **Verify against the code')
  out.push('before acting on anything here.** Listed wherever they physically live — closure is')
  out.push('carried by `status:`, not by which folder a file sits in.')
  out.push('')
  for (const d of past.sort((a, b) => b.rel.localeCompare(a.rel))) out.push(line(d))
  out.push('')
}

const content = out.join('\n')

if (process.argv.includes('--check')) {
  let current = ''
  try { current = readFileSync(OUT, 'utf8') } catch {}
  if (current !== content) {
    console.error('docs-index: docs/README.md is stale. Run `pnpm docs:index` and commit the result.')
    process.exit(1)
  }
  console.log(`docs-index: docs/README.md is current (${docs.length} documents)`)
  process.exit(0)
}

writeFileSync(OUT, content)
console.log(`docs-index: wrote docs/README.md (${docs.length} documents)`)
